export const en = {
    login: {
        passwordLogin: 'Password login',
        loginTitle: 'Global residential proxy IP enterprise-level big data collection solution',
        phonePlaceholder: 'Please enter your phone number/account number',
        passwordPlaceholder: 'Please enter your password',
        agree: 'I have read and agree',
        userServiceAgreement: 'BITIP User Service Agreement',
        privacyPolicy:'BITIP Privacy Policy',
        smsLogin: 'SMS login',
        login: 'Login',
        forgetPassword:'Forget the password',
        notAccount: 'No account yet?',
        registerNow: 'Register Now',
        phoneValidate: 'Please enter your phone number or account number',
        passwordValidate: 'Please enter your password',
        phoneTips: 'Mobile phone/account',
        passwordTips: 'Password',
        modalPolicy:'Service Agreement and Privacy Protection',
        modalTips: 'In order to provide you with better services and protect the legitimate rights and interests of users, please read and agree to the following agreement',
        agreeLogin: 'Agree and log in',
        disagree: 'Disagree',
        textLogin: 'Please enter your phone number',
        textTips: 'Mobile phone',
        textValidate: 'Please enter a valid phone number',
        verifyCode: 'Please enter the verification code',
        sendCode: 'SMS VC​',
        verifyTips: 'Verification code',
        register: 'Register',
        haveAccount:'Already have an account?',
        passwordValidateNew: 'Please enter a 6-12 digit password',
        confirmMessage: 'Confirm',
        email: 'Email',
        emailValidate: 'Please enter a valid email address',
        emailPlaceholder: 'Please enter your email address',
        finshSetting: 'Completed setup?',
        newPassword: 'Please enter new password',
        confirmPassword:'The two passwords do not match',
        confirmPassTips: 'Confirm Password',
        captchaVerifyTitps: 'Please slide the verification code',
        sendSms:'Sent, please check',
        exit:'Log out'
    },
    first: {
        title:'Bit Global Residential Proxy IP',
        subtitle:'Enterprise-level big data collection solutions',
        item1:'Billion+ Real Residential Network',
        item2:'IP Pure Source Compliance',
        item3:'99.9% connectivity rate',
        item4:'24/7 AI Screening',
        freeUse: 'Free Trial',
        contact: 'Contact Us',
        cardTitle1:'Accurate city positioning',
        cardContent1:'Dynamic global coverage and precise geolocation, supporting IP rotation',
        cardTitle2:'High cost performance',
        cardContent2: 'Relying on industry-leading agent resources to achieve automatic collection of global web page data',
        cardTitle3: 'Residential ISP',
        cardContent3: 'Select high-purity native static IPs to safely manage various e-commerce accounts.',
        cardTitle4: 'Sub-account management',
        cardContent4: 'Sub-account management Enterprise-level account management, real-time traffic monitoring',
        cardTitle5: 'Technical Support',
        cardContent5: 'Technical Support Professional team 1V1 full support, providing customized solutions'
    },
    second: {
        title: 'High purity and high stability proxy IP',
        select1:'DRIP',
        select2: 'SRIP',
        dynamicContent: 'Real residential devices from around the world, suitable for business scenarios with large IP quantity requirements and short-term use',
        dynamicItem1: 'million+ high-purity residential IP pools',
        dynamicItem2: 'Unlimited concurrent requests',
        dynamicItem3: '1-120min variable IP validity',
        dynamicItem4: 'Support Http/Https/Socks5 protocols',
        dynamicItem5: 'Support API access, more stable network',
        dynamicButton:'Free Trial'
    },
    third: {
        title: 'Service and scale',
        item1title: 'Global Resources',
        item1Subtitle:'Billions of proxy resource pools',
        item1Content:'IPIDEA builds its own enterprise-level pure IP pool and strictly screens more than 100 million high-quality IP resources to meet the needs of large-scale data collection and effectively reduce enterprise costs.',
        item2title: 'Professional Team',
        item2Subtitle:'Billions of proxy resource pools',
        item2Content:'IPIDEA builds its own enterprise-level pure IP pool and strictly screens more than 100 million high-quality IP resources to meet the needs of large-scale data collection and effectively reduce enterprise costs.',
        item3title: 'High cost performance',
        item3Subtitle:'Billions of proxy resource pools',
        item3Content:'IPIDEA builds its own enterprise-level pure IP pool and strictly screens more than 100 million high-quality IP resources to meet the needs of large-scale data collection and effectively reduce enterprise costs.',
        item4title: 'Safe and reliable',
        item4Subtitle:'Billions of proxy resource pools',
        item4Content:'IPIDEA builds its own enterprise-level pure IP pool and strictly screens more than 100 million high-quality IP resources to meet the needs of large-scale data collection and effectively reduce enterprise costs.',
        item5title: 'High anonymity',
        item5Subtitle:'Billions of proxy resource pools',
        item5Content:'IPIDEA builds its own enterprise-level pure IP pool and strictly screens more than 100 million high-quality IP resources to meet the needs of large-scale data collection and effectively reduce enterprise costs.'
    },
    fourth: {
        title: 'Unlock global network resources to empower your digital business',
        subtitle1: '220+',
        content1: 'Available regions worldwide',
        subtitle2: 'Billion level',
        content2: 'Carrying Concurrency',
        subtitle3: '99.9%',
        content3: 'High IP availability'
    },
    fifth: {
        title: 'Application Scenario',
        subtitle1: 'Data scraping and crawling',
        content1: 'Master global network data resources, extract valuable information from tens of millions of web pages for analysis, and support your business decisions',
        subtitle2: 'Ad Verification',
        content2: 'Master global network data resources, extract valuable information from tens of millions of web pages for analysis, and support your business decisions',
        subtitle3: 'Price monitoring',
        content3: 'Master global network data resources, extract valuable information from tens of millions of web pages for analysis, and support your business decisions',
        subtitle4: 'Crawl Proxy',
        content4: 'Master global network data resources, extract valuable information from tens of millions of web pages for analysis, and support your business decisions',
        subtitle5: 'Crawl Proxy',
        content5: 'Master global network data resources, extract valuable information from tens of millions of web pages for analysis, and support your business decisions',
        subtitle6: 'Crawl Proxy',
        content6: 'Master global network data resources, extract valuable information from tens of millions of web pages for analysis, and support your business decisions',
        more: 'Learn more'
    },
    sixth: {
        title: 'Open a new chapter of multi-account management with BitIP',
        content: 'Free trial of 5 browser environments',
        button1: 'Free Trial',
        button2: 'Contact Us'
    },
    seventh: {
        title: 'Many corporate brand cooperation'
    },
    acvitity: {
        title: 'Residential Agency First Payment',
        subtitle: '¥100 off'
    },
    contact: {
        title1: 'QQ',
        title2: 'WeChat',
        title3: 'Official',
        title4: 'Telegram'
    },
    navMenu: {
        title1: 'Package Purchase',
        package_title1:'Credit Recharge',
        package_title2:'Product Packages',
        package_subtitle1: 'Dynamic Residential IP',
        package_subtitle2:'Static Residential IP',
        package_subtitle3: 'Dynamic Residential Package',
        package_subtitle4: 'Static Residential Package',
        package_subtitle1_tips:'As low as ¥4.5/GB',
        package_subtitle2_tips:'Exclusive original ultra-pure',
        package_subtitle3_tips:'Dynamic Residential Package',
        package_title3: 'Latest Events',
        title2: 'Get a proxy',
        title3:'Agent Products',
        title4: 'Help Center',
        title5: 'Safety and Compliance',
        title6: 'Corporate Services',
        title7: 'Promotion Plan'
    },
    footer: {
        describe: 'With strong global underlying resources and understanding of business scenarios in various industries',
        describe1:'bitip is providing nanny-level proxy IP services',
        title1: '代理',
        title1_subtitle1: '住宅代理',
        title1_subtitle2: 'ISP代理',
        title1_subtitle3:'不限量住宅代理',
        title1_subtitle4:'数据中心代理',
        title1_subtitle5: '获取代理',
        title2: '代理',
        title2_subtitle1: '住宅代理',
        title2_subtitle2: 'ISP代理',
        title2_subtitle3:'不限量住宅代理',
        title2_subtitle4:'数据中心代理',
        title2_subtitle5: '获取代理',
        title3: '代理',
        title3_subtitle1: '住宅代理',
        title3_subtitle2: 'ISP代理',
        title3_subtitle3:'不限量住宅代理',
        title3_subtitle4:'数据中心代理',
        title3_subtitle5: '获取代理',
        title4: '代理',
        title4_subtitle1: '住宅代理',
        title4_subtitle2: 'ISP代理',
        title4_subtitle3:'不限量住宅代理',
        title4_subtitle4:'数据中心代理',
        title4_subtitle5: '获取代理',
    },
    safety: {
        title: 'Build a safe, compliant and healthy big data service ecosystem',
        subtitle: 'IPIDEA always adheres to the principles of security and compliance, and is committed to providing safe, stable, and high-quality big data proxy services, protecting the legitimate rights and interests of users, and promoting the healthy and orderly development of global big data business.',
        title2: 'Safety and Compliance Management',
        subtitle2: 'Comply with national laws and regulations and implement industry safety control measures',
        title2_item1_title: 'Real-name authentication',
        title2_item1_content: 'Users need to complete real-name authentication and pass verification before they can use IPIDEA proxy products',
        title2_item2_title: 'Account Security',
        title2_item2_content: 'Users need to complete real-name authentication and pass verification before they can use IP IDEA proxy products.',
        title2_item3_title: 'Risk Management',
        title2_item3_content: 'Conduct risk management on product usage scenarios and objectives, and implement supervision and handling measures for improper behavior',
        title3: 'Safety Standards',
        subtitle3: 'Comply with ISO9001 quality management system, ISO27001 information security management system and other high industry standards',
        title3_item1_title1: 'ISO 27001',
        title3_item1_content: 'Information Security Management System',
        title3_item2_title2:'ISO 9001',
        title3_item2_content: 'Quality Management System'
    }
}

export const zh = {
    login: {
        passwordLogin: '密码登录',
        smsLogin: '短信登录',
        loginTitle: '全球住宅代理IP企业级 大数据采集解决方案',
        phonePlaceholder: '请输入手机号/账号',
        passwordPlaceholder: '请输入密码',
        agree: '我已阅读并同意',
        userServiceAgreement: 'BITIP用户服务协议',
        privacyPolicy: 'BITIP隐私协议',
        login: '登录',
        forgetPassword: '忘记密码',
        notAccount:'暂无账号?',
        registerNow: '立即注册',
        phoneValidate: '请输入手机或者账号',
        passwordValidate: '请输入密码',
        phoneTips: '手机 / 账号',
        passwordTips: '密码',
        modalPolicy: '服务协议及隐私保护',
        modalTips: '为了更好地为您提供服务，保障用户合法权益，帮请您阅读并同意以下协议',
        agreeLogin: '同意并登录',
        disagree: '不同意',
        textLogin: '请输入手机号',
        textTips: '手机',
        textValidate: '请输入正确的手机号',
        verifyCode: '请输入验证码',
        sendCode: '发送验证码',
        verifyTips: '验证码',
        register:'注册',
        haveAccount:'已有账号?',
        passwordValidateNew: '请输入6-12位的密码',
        confirmMessage: '确认',
        email:'邮箱',
        emailValidate:'请输入合法的邮箱',
        emailPlaceholder: '请输入邮箱',
        finshSetting: '已完成设置?',
        newPassword: '请输入新密码',
        confirmPassword: '两次密码不一致',
        confirmPassTips: '确认密码',
        captchaVerifyTitps: '请滑动验证码',
        sendSms:'已发送,请查收',
        exit:'退出登录'
    },
    first: {
        title:'Bit全球住宅代理IP',
        subtitle:'企业级大数据采集解决方案',
        item1:'亿+真实住宅网络',
        item2:'IP纯净来源合规',
        item3:'99.9%连通率',
        item4:'7X24 AI筛选',
        freeUse:'免费试用',
        contact:'联系我们',
        cardTitle1:'精确城市定位',
        cardContent1:'动态全球覆盖和精准的地理定位，支持IP轮换',
        cardTitle2:'高性价比',
        cardContent2: '依托行业领先的代理资源,实现全球网页数据自动化采集',
        cardTitle3: '住宅ISP',
        cardContent3: '精选高纯净度原生静态IP，安全管理各类电商账号。',
        cardTitle4: '子账号管理',
        cardContent4: '子账号管理 企业级账号管理，实时监控流量',
        cardTitle5: '技术支持',
        cardContent5: '技术支持 专业团队1V1全程支持，提供定制化解决方案'
    },
    second: {
        title: '高纯净、高稳定性代理IP',
        select1:'动态住宅代理',
        select2: '静态住宅代理',
        dynamicContent: '来自全球真实家庭住宅设备，适用于IP数量需求 大且短时使用的业务场景',
        dynamicItem1: '亿+高纯净家庭住宅IP池',
        dynamicItem2: '无限并发请求',
        dynamicItem3: '1-120min 可变IP时效',
        dynamicItem4: '支持Http/Https/Socks5协议',
        dynamicItem5: '支持API接入，网络更稳定',
        dynamicButton:'免费试用'
    },
    third: {
        title: '服务与规模',
        item1title: '全球资源',
        item1Subtitle:'亿级代理资源池',
        item1Content:'IPIDEA自建企业级纯净IP池，严格筛选1亿多个优质IP资源，满足企业 大规模数据采集业务，有效降低企业成本',
        item2title: '专业团队',
        item2Subtitle:'亿级代理资源池',
        item2Content:'IPIDEA自建企业级纯净IP池，严格筛选1亿多个优质IP资源，满足企业 大规模数据采集业务，有效降低企业成本',
        item3title: '高性价比',
        item3Subtitle:'亿级代理资源池',
        item3Content:'IPIDEA自建企业级纯净IP池，严格筛选1亿多个优质IP资源，满足企业 大规模数据采集业务，有效降低企业成本',
        item4title: '安全可靠',
        item4Subtitle:'亿级代理资源池',
        item4Content:'IPIDEA自建企业级纯净IP池，严格筛选1亿多个优质IP资源，满足企业 大规模数据采集业务，有效降低企业成本',
        item5title: '高匿名性',
        item5Subtitle:'亿级代理资源池',
        item5Content:'IPIDEA自建企业级纯净IP池，严格筛选1亿多个优质IP资源，满足企业 大规模数据采集业务，有效降低企业成本'
    },
    fourth: {
        title: '解锁全球网络资源，赋能您的数字业务',
        subtitle1: '220+',
        content1: '全球可选地区',
        subtitle2: '亿级',
        content2: '承载并发',
        subtitle3: '99.9%',
        content3: '高IP可用率'
    },
    fifth: {
        title: '应用场景',
        subtitle1: '数据抓取与爬虫',
        content1: '掌握全球网络数据资源，从数千万网页中提取有价值 的信息进行分析，为您的业务决策提供支持',
        subtitle2: '广告验证',
        content2: '掌握全球网络数据资源，从数千万网页中提取有价值 的信息进行分析，为您的业务决策提供支持',
        subtitle3: '价格监控',
        content3: '掌握全球网络数据资源，从数千万网页中提取有价值的信息进行分析，为您的业务决策提供支持',
        subtitle4: '抓取代理',
        content4: '掌握全球网络数据资源，从数千万网页中提取有价值 的信息进行分析，为您的业务决策提供支持',
        subtitle5: '抓取代理',
        content5: '掌握全球网络数据资源，从数千万网页中提取有价值 的信息进行分析，为您的业务决策提供支持',
        subtitle6: '抓取代理',
        content6: '掌握全球网络数据资源，从数千万网页中提取有价值 的信息进行分析，为您的业务决策提供支持',
        more: '了解更多'
    },
    sixth: {
        title: '与BitIP一起，开启多账号管理新篇章',
        content: '免费体验5个浏览器环境',
        button1: '免费试用',
        button2: '联系我们'
    },
    seventh: {
        title: '众多企业品牌合作'
    },
    acvitity: {
        title: '住宅代理首次支付',
        subtitle: '立减¥100'
    },
    contact: {
        title1: 'QQ客服',
        title2: '微信客服',
        title3: '微信公众号',
        title4: '电报客服'
    },
    navMenu: {
        title1: '套餐购买',
        package_title1:'套餐购买',
        package_title2:'产品套餐',
        package_subtitle1: '动态住宅IP',
        package_subtitle1_tips:'低至¥4.5/GB',
        package_subtitle2:'静态住宅IP',
        package_subtitle2_tips:'独享原生超纯净',
        package_subtitle3: '动态住宅套餐',
        package_subtitle3_tips:'动态住宅套餐',
        package_subtitle4: '静态住宅套餐',
        package_title3: '最新活动',
        title2: '获取代理',
        title3:'代理产品',
        title4: '帮助中心',
        title5: '安全合规',
        title6: '企业服务',
        title7: '推广计划'
    },
    footer: {
        describe: '凭借着强大的全球底层资源及对各个行业业务场景的了解',
        describe1:'bitip正以保姆级的代理IP服务',
        title1: '代理',
        title1_subtitle1: '住宅代理',
        title1_subtitle2: 'ISP代理',
        title1_subtitle3:'不限量住宅代理',
        title1_subtitle4:'数据中心代理',
        title1_subtitle5: '获取代理',
        title2: '代理',
        title2_subtitle1: '住宅代理',
        title2_subtitle2: 'ISP代理',
        title2_subtitle3:'不限量住宅代理',
        title2_subtitle4:'数据中心代理',
        title2_subtitle5: '获取代理',
        title3: '代理',
        title3_subtitle1: '住宅代理',
        title3_subtitle2: 'ISP代理',
        title3_subtitle3:'不限量住宅代理',
        title3_subtitle4:'数据中心代理',
        title3_subtitle5: '获取代理',
        title4: '代理',
        title4_subtitle1: '住宅代理',
        title4_subtitle2: 'ISP代理',
        title4_subtitle3:'不限量住宅代理',
        title4_subtitle4:'数据中心代理',
        title4_subtitle5: '获取代理',
    },
    safety: {
        title: '构建安全、合规、健康的 大数据服务生态',
        subtitle: 'IPIDEA始终坚守安全合规原则，致力于提供安全、稳定、优质的大数据代理服务，保障用户合法权益，推动 全球大数据业务的健康有序发展',
        title2: '安全合规管理',
        subtitle2: '遵守国家法律法规，实施行业安全管控措施',
        title2_item1_title: '实名认证',
        title2_item1_content: '用户需要完成实名认证并核验通过， 才能使用IPIDEA代理产品',
        title2_item2_title: '账户安全',
        title2_item2_content: '用户需要完成实名认证并核验通过，用户需要完成实名认证并核验通过，才能使用IP IDEA代理产品才能使用IPIDEA代理产品',
        title2_item3_title: '风险管控',
        title2_item3_content: '对产品使用场景、目标进行风险管控， 且针对不当行为执行监管、处理措施',
        title3: '安全标准',
        subtitle3: '符合ISO9001质量管理体系，ISO27001信息安全管理体系等行业高标准',
        title3_item1_title1: 'ISO 27001',
        title3_item1_content: '信息安全管理体系',
        title3_item2_title2:'ISO 9001',
        title3_item2_content: '质量管理体系'
    }
}