export const en = {
    login: {
        passwordLogin: 'Password login',
        loginTitle: 'Global residential proxy IP enterprise-level big data collection solution',
        phonePlaceholder: 'Please enter your phone number/account number',
        passwordPlaceholder: 'Please enter your password',
        agree: 'I have read and agree',
        userServiceAgreement: 'BITIP User Service Agreement',
        privacyPolicy:'BITIP Privacy Policy',
        smsLogin: 'SMS login',
        login: 'Login',
        forgetPassword:'Forget the password',
        notAccount: 'No account yet?',
        registerNow: 'Register Now',
        phoneValidate: 'Please enter your phone number or account number',
        passwordValidate: 'Please enter your password',
        phoneTips: 'Mobile phone/account',
        passwordTips: 'Password',
        modalPolicy:'Service Agreement and Privacy Protection',
        modalTips: 'In order to provide you with better services and protect the legitimate rights and interests of users, please read and agree to the following agreement',
        agreeLogin: 'Agree and log in',
        disagree: 'Disagree',
        textLogin: 'Please enter your phone number',
        textTips: 'Mobile phone',
        textValidate: 'Please enter a valid phone number',
        verifyCode: 'Please enter the verification code',
        sendCode: 'Send verification code',
        verifyTips: 'Verification code',
        register: 'Register',
        haveAccount:'Already have an account?',
        passwordValidateNew: 'Please enter a 6-12 digit password',
        confirmMessage: 'Confirm',
        email: 'Email',
        emailValidate: 'Please enter a valid email address',
        emailPlaceholder: 'Please enter your email address',
        finshSetting: 'Completed setup?',
        newPassword: 'Please enter new password'
    },
    first: {
        title:'Bit Global Residential Proxy IP',
        subtitle:'Enterprise-level big data collection solutions',
        item1:'Billion+ Real Residential Network',
        item2:'IP Pure Source Compliance',
        item3:'99.9% connectivity rate',
        item4:'24/7 AI Screening',
        freeUse: 'Free Trial',
        contact: 'Contact Us'
    }
}

export const zh = {
    login: {
        passwordLogin: '密码登录',
        smsLogin: '短信登录',
        loginTitle: '全球住宅代理IP企业级 大数据采集解决方案',
        phonePlaceholder: '请输入手机号/账号',
        passwordPlaceholder: '请输入密码',
        agree: '我已阅读并同意',
        userServiceAgreement: 'BITIP用户服务协议',
        privacyPolicy: 'BITIP隐私协议',
        login: '登录',
        forgetPassword: '忘记密码',
        notAccount:'暂无账号?',
        registerNow: '立即注册',
        phoneValidate: '请输入手机或者账号',
        passwordValidate: '请输入密码',
        phoneTips: '手机 / 账号',
        passwordTips: '密码',
        modalPolicy: '服务协议及隐私保护',
        modalTips: '为了更好地为您提供服务，保障用户合法权益，帮请您阅读并同意以下协议',
        agreeLogin: '同意并登录',
        disagree: '不同意',
        textLogin: '请输入手机号',
        textTips: '手机',
        textValidate: '请输入正确的手机号',
        verifyCode: '请输入验证码',
        sendCode: '发送验证码',
        verifyTips: '验证码',
        register:'注册',
        haveAccount:'已有账号?',
        passwordValidateNew: '请输入6-12位的密码',
        confirmMessage: '确认',
        email:'邮箱',
        emailValidate:'请输入合法的邮箱',
        emailPlaceholder: '请输入邮箱',
        finshSetting: '已完成设置?',
        newPassword: '请输入新密码'
    },
    first: {
        title:'Bit全球住宅代理IP',
        subtitle:'企业级大数据采集解决方案',
        item1:'亿+真实住宅网络',
        item2:'IP纯净来源合规',
        item3:'99.9%连通率',
        item4:'7X24 AI筛选',
        freeUse:'免费试用',
        contact:'联系我们'

    }
}