export const en = {
    login: {
        passwordLogin: 'Password login',
        loginTitle: 'Global residential proxy IP enterprise-level big data collection solution',
        phonePlaceholder: 'Please enter your phone number/account number',
        passwordPlaceholder: 'Please enter your password',
        agree: 'I have read and agree',
        userServiceAgreement: 'BITIP User Service Agreement',
        privacyPolicy:'BITIP Privacy Policy',
        smsLogin: 'SMS login',
        login: 'Login',
        forgetPassword:'Forget the password',
        notAccount: 'No account yet?',
        registerNow: 'Register Now',
        phoneValidate: 'Please enter your phone number or account number',
        passwordValidate: 'Please enter your password',
        phoneTips: 'Mobile phone/account',
        passwordTips: 'Password',
        modalPolicy:'Service Agreement and Privacy Protection',
        modalTips: 'In order to provide you with better services and protect the legitimate rights and interests of users, please read and agree to the following agreement',
        agreeLogin: 'Agree and log in',
        disagree: 'Disagree',
        textLogin: 'Please enter your phone number',
        textTips: 'Mobile phone',
        textValidate: 'Please enter a valid phone number',
        verifyCode: 'Please enter the verification code',
        sendCode: 'SMS VC​',
        verifyTips: 'Verification code',
        register: 'Register',
        haveAccount:'Already have an account?',
        passwordValidateNew: 'Please enter a 6-12 digit password',
        confirmMessage: 'Confirm',
        email: 'Email',
        emailValidate: 'Please enter a valid email address',
        emailPlaceholder: 'Please enter your email address',
        finshSetting: 'Completed setup?',
        newPassword: 'Please enter new password',
        confirmPassword:'The two passwords do not match',
        confirmPassTips: 'Confirm Password',
        captchaVerifyTitps: 'Please slide the verification code',
        sendSms:'Sent, please check',
        exit:'Log out',
        Backstage: 'Dashboard',
        registerTip:'Get 200M',
        modityTips:'Modification successful',
        registerSuccess:'Successful registration',
        newPassTip:'New Password',
        modifyMessage:'Modify Success'
    },
    first: {
        title:' Global Residential Proxy',
        // title:'全球住宅代理IP',
        title1:'Bit',
        content:'The real residential network covers more than',
        content2:'countries, supports multi-scenario data collection with high speed and stability, and intelligent routing ensures privacy and security, helping companies to efficiently expand into the global market!',        
        subtitle:'Enterprise-level big data collection solutions',
        item1:'Billion+ Real Residential Network',
        item2:'IP Pure Source Compliance',
        item3:'99.9% connectivity rate',
        item4:'24/7 AI Screening',
        freeUse: 'Free Trial',
        contact: 'Contact Us',
        cardTitle1:'City-level positioning',
        cardTitle2:'SOCKS5/HTTP/HTTPS Protocol',
        cardContent2: 'Communication protocols are encrypted using a proprietary algorithm',
        // cardContent2: 'Relying on industry-leading agent resources to achieve automatic collection of global web page data',
        cardTitle3: 'Residential ISP',
        cardContent3: 'Select high-purity native static IPs to safely manage various e-commerce accounts.',
        cardTitle4: 'Sub-account management',
        cardContent4: 'Sub-account management Enterprise-level account management, real-time traffic monitoring',
        cardTitle5: 'Technical Support',
        cardContent5: 'Technical Support Professional team 1V1 full support, providing customized solutions',
        tips: '(All products only support network environments outside mainland China)'
    },
    second: {
        title: 'High purity and high stability proxy IP',
        select1:'DRIP',
        select2: 'SRIP',
        dynamicContent: 'Real residential devices from around the world, suitable for business scenarios with large IP quantity requirements and short-term use',
        dynamicItem1: 'million+ high-purity residential IP pools',
        dynamicItem2: 'Unlimited concurrent requests',
        dynamicItem3: '1-120min variable IP validity',
        dynamicItem4: 'Support Http/Https/Socks5 protocols',
        dynamicItem5: 'Support API access, more stable network',
        dynamicButton:'Free Trial',
        dynamicContent1:'Fixed long-term native IP, suitable for business scenarios that require a more stable and pure network environment, such as e-commerce account management, social media marketing, and enterprise acceleration',
        dynamicItem6:'Carefully selected authentic, pure, native residential IP',
        dynamicItem7:'Unlimited traffic, unimpeded use',
        dynamicItem8:'Support Http/Https/Socks5 protocols',
        dynamicItem9:'Real-time delivery, no waiting',
        dynamicButton1:'Learn More'
    },
    third: {
        title: 'Service and scale',
        item1title: 'Global Resources',
        item1Subtitle:'Global Resources',
        item1Content:'Cooperate with many ISPs around the world to ensure the richness and stability of IP resources.',
        item2title: 'Professional team',
        item2Subtitle:'Billion-level agent resource pool',
        item2Content:'IPIDEA built its own enterprise-level pure IP pool, strictly screening more than 100 million high-quality IP resources to meet the large-scale data collection business of enterprises, effectively reducing enterprise costs',
        item3title: 'High cost performance',
        item3Subtitle:'High cost performance',
        item3Content:'Cooperate with many ISPs around the world to ensure the richness and stability of IP resources.',
        item4title: 'Safe and reliable',
        item4Subtitle:'Safe and reliable',
        item4Content:'Strict data protection measures ensure the security of your data.',
        item5title: 'High anonymity',
        item5Subtitle:'High anonymity',
        item5Content:'All IPs are from real home broadband users, ensuring high anonymity and low ban rates.'
    },
    fourth: {
        title: 'Unlock global network resources to empower your digital business',
        subtitle1: '220+',
        content1: 'Available regions worldwide',
        subtitle2: 'Billion level',
        content2: 'Carrying Concurrency',
        subtitle3: '99.9%',
        content3: 'High IP availability',
        ger:'GER',
        us: 'US',
        uk:'UK',
        can:'CAN',
        ind:'IND'
    },
    fifth: {
        title: 'Application Scenario',
        subtitle1: 'Data scraping and crawling',
        content1: 'Capture data from e-commerce, social media, search engines, etc. to avoid IP blocking. Support high-frequency requests and large-scale data collection.',
        subtitle2: 'Ad Verification',
        content2: 'Verify the display effect of advertisements in different regions and ensure the accuracy of advertisement delivery. Simulate real user behavior and obtain real advertisement data.',
        subtitle3: 'Price monitoring',
        content3: 'Monitor competitors price changes and obtain market dynamics. Support price monitoring in multiple regions and platforms.',
        subtitle4: 'SEO Monitoring',
        content4: 'Check the website search ranking in different regions and optimize SEO strategies. Support multi-search engine and multi-keyword monitoring.',
        subtitle5: 'Social Media Management',
        content5: 'Manage multiple social media accounts to avoid account association. Support multi-platform and multi-account automation operations.',
        subtitle6: 'Market Research',
        content6: 'Obtain market data from different regions to support business decisions. Support multi-language and multi-region research needs.',
        more: '了解更多'
    },
    sixth: {
        title: 'Opening the borderless door to the global network',
        content: 'Free trial of 5 browser environments',
        button1: 'Free Trial',
        button2: 'Contact Us'
    },
    seventh: {
        title: 'Integrate into your tools'
    },
    acvitity: {
        title: 'Register and get 200M dynamic traffic',
        subtitle: '¥100 off',
        
    },
    contact: {
        title1: 'QQ',
        title2: 'WeChat',
        title3: 'Official',
        title4: 'Telegram'
    },
    navMenu: {
        title1: 'Package Purchase',
        package_title1:'Credit Recharge',
        package_title2:'Balance Recharge',
        package_subtitle1: 'Dynamic Residential IP',
        package_subtitle2:'Static Residential IP',
        package_subtitle3: 'Recharge and get free',
        package_subtitle4: 'Static Residential Package',
        package_subtitle1_tips:'As low as ¥4.5/GB',
        package_subtitle2_tips:'Exclusive original ultra-pure',
        package_subtitle3_tips:'Dynamic Residential Package',
        package_title3: 'Latest Events',
        title2: 'Dy Agent',
        title3:'Agent Products',
        title4: 'Help Center',
        title5: 'Safety and Compliance',
        title6: 'Enterprise customization',
        title7: 'Promotion Plan',
        title8: 'Static agency'
    },
    footer: {
        describe: 'Phone/WeChat',
        title1: 'BitIP',
        title1_subtitle1: 'Dynamic Residential Proxy',
        title1_subtitle2: 'Static Residential Proxies',

        title2: 'Tutorial Center',
        title2_subtitle1: 'API Documentation',
        title2_subtitle2: 'Product Usage Tutorial',
        title3: 'About Us',
        title3_subtitle1: 'Privacy Policy',
        title3_subtitle2: 'Service Agreement',
        title3_subtitle3:'Safety and Compliance',
        title3_subtitle4:'Enterprise customization',
        title3_subtitle5: 'Promotion Plan',
        title3_subtitle6: 'Partners',
        title4_subtitle7:'Refund Agreement',
        title4: 'Global Agents',
        title4_subtitle1: 'U.S. Native Family Bandwidth',
        title4_subtitle2: 'UK home bandwidth',
        title4_subtitle3:'German native family bandwidth',
        title4_subtitle4:'Singaporean family bandwidth',
        title4_subtitle5: 'Bandwidth of native families in Thailand',
       
    },
    safety: {
        title: 'Provide a safe and reliable network environment for your business',
        subtitle: 'In the digital age, data security and compliance are the keys to business success. BITIP always puts security first and is committed to providing users with safe, compliant and reliable proxy services to ensure that your business is worry-free around the world.',
        title2: `BITIP's Security Commitment`,
        subtitle2: 'BITIP uses advanced encryption technology (such as SSL/TLS) to ensure that your data is always encrypted during transmission to prevent theft or tampering. We strictly abide by the privacy protection policy and never disclose user data.',
        title2_item1_title: 'Real-time monitoring and threat prevention',
        title2_item1_content: `BITIP's security team monitors network traffic in real time 24/7, quickly identifying and defending against potential network attacks (such as DDoS, malicious crawlers, etc.), ensuring that your business always runs stably.`,
        title2_item2_title: 'Compliance and transparency',
        title2_item2_content: 'We strictly abide by the laws and regulations of major countries and regions around the world to ensure that your business operates in compliance with regulations worldwide. At the same time, we provide transparent service agreements and usage policies so that you can clearly understand how your data is used.',
        title2_item3_title: 'Zero-logging policy',
        title2_item3_content: `BITIP adopts a strict zero-log policy and does not record users' browsing history, access data or any sensitive information, ensuring that your privacy is protected to the greatest extent.`,
        title3: 'Safety Standards',
        subtitle3: 'Comply with ISO27001 information security management system, SOC 2 compliance standards and other high industry standards',
        title3_item1_title1: 'ISO 27001',
        title3_item1_content: 'Information Security Management System',
        title3_item2_title2:'SOC 2',
        title3_item2_content: 'Compliance Standards'
    },
    service: {
        title1: 'Enterprise Customization Service',
        content1: `In today's digital age, companies need efficient and reliable network tools to cope with complex business needs. BITIP is well aware of the uniqueness of each company, so we provide customized services for companies, tailor-made agent solutions for you, and help your business expand globally without boundaries.`,
        title2: 'Customization',
        title2_subtitle1: 'Highly customizable',
        title2_content1: 'Based on your business needs, we provide a full range of customized services from IP type, geographic location to concurrent connections to ensure that your network tools fully match your business scenarios.',
        title2_subtitle2: 'Professional team support',
        title2_content2: 'BITIP has an experienced technical team that provides you with 7x24 hours of professional support to ensure that your business always runs smoothly.',
        title2_subtitle3: 'Security and Privacy',
        title2_content3: 'We use advanced encryption technology and strict data protection measures to ensure that your business data is safe and secure.',
        title3:'Customization process',
        title3_title1:'Demand communication',
        title3_title1_content:'Talk to our team of experts to understand your business needs and goals.',
        title3_title2:'Solution Design',
        title3_title2_content:'We can customize proxy solutions based on your needs, including IP type, geographic location, number of concurrent connections, etc.',
        title3_title3:'Deployment and testing',
        title3_title3_content:'Rapidly deploy customized solutions and conduct comprehensive testing to ensure performance meets expectations.',
        title3_title4:'Continuous Optimization',
        title3_title4_content:'We will continue to optimize our agent services based on business development to ensure that your needs are always met.',
        title4:'The common choice of many companies'
    },
    setmenu: {
        title: 'BitIP Agent Discount Package Type',
        subtitle1: 'Dy Setmenu',
        subtitle2: 'Static Setmenu',
        subtitle3: 'Balance Recharge',
        discount:'Discount Purchase',
        menu1: 'Started',
        price:'Unit price',
        originPrice:'Original Price',
        menu2: 'Base',

        menu3: 'Routine',

        menu4: 'Pro',

        menu5: 'Company',

        menu6: 'Unlimited',
        menu6_title:'Custom',
        menu6_button:'Contact customer service',
        title2:'What is included in the setmenu?',
        content1: 'Data usage does not expire',
        content2: 'Large IP pool of 100 million',
        content3: 'Unlimited concurrency',
        content4: 'Variable time limit',
        content5: 'Accurate city positioning',
        content6:' Sub-account traffic allocation',
        bottom_title: 'Frequently asked questions',
        question1:'What is the difference between product packages and using agents for credit recharge?',
        answer1: '',
        question2:'What is the difference between product packages and using agents for credit recharge?',
        answer2: '',
        question3:'What is the difference between product packages and using agents for credit recharge?',
        answer3: '',
        question4:'What is the difference between product packages and using agents for credit recharge?',
        answer4: '',
        question5:'What is the difference between product packages and using agents for credit recharge?',
        answer5: '',
        question6:'What is the difference between product packages and using agents for credit recharge?',
        answer6: '',

        location:'Native Residential double ISP',
        location2:'Residential Single ISP',
        type1:'Single ISP',
        type2:'Dual ISP',
        timeSelect:'Time selection',
        time1:'1 month',
        time2:'2 months',
        time3: 'One quarter',
        time4:'Half a year',
        time5: 'one year',
        off: 'off',
        clear:'clear',
        areas:'Total Region',
        ips: 'Total IP',
        allPrice: 'Total price',
        buyButton: 'Buy it now',
        number:'each one',
        arrival: 'Arrival',
        recharge: 'Recharge',
        deliver: 'Ddeliver',

        recharge_title: 'Recharge the balance',
        recharge_subtitle: 'The balance can be used to purchase dynamic and static packages and renewals',
        illustrate: 'Optimized price instructions'
    },
    backend_menu: {
        menu1:'Dynamic Residence',
        menu1_sub1:'Proxy Generation',
        menu1_sub2:'Purchase Flow',
        menu1_sub3: 'Traffic Management',
        menu2: 'Static Residence',
        menu2_sub1: 'Purchase Agent',
        menu2_sub2:'Purchased Agent',
        menu3: 'Purchase history',
        menu4: 'Promotion rebate',
        menu5:'User Auth',
        local:'Current IP',
        Balance:'Balance',
        recharge:'Recharge',
        welcome:'Welcome',
        account: 'Account',
        authentication:'Real-name authentication',
        setting:'Account Settings',
        tip:'(All products only support network environments outside mainland China)'
    },
    proxycity: {
        card_title1: 'Remain flow',
        card_title2:'Total flow',
        card_title3: 'Used flow',
        card_button:'Purchase flow',
        card_button1:'Traffic Management',
        card_button_title:'Add sub-account',
        describe1: 'describe1',
        describe2: 'describe2',
        describe3: 'describe3',
        card1: 'Dynamic residential proxy generation',
        card2:'card2',

        form1:'Select certified account',
        form1_placeholder: 'Please select',
        form2:'Choose country',
        form2_placeholder: 'Please select',
        form3: 'Choose region',
        form3_placeholder:'Please select',
        form4: 'Choose city',
        form4_placeholder:'Please select',
        form5: 'IP time',
        form5_placeholder: 'Please select',
        form6: 'Switch IP',
        form6_placeholder:'Automatically switch IP',
        form7_placeholder: 'Please select',
        form7: 'Select quantity',
        button1: 'Generate proxy IP',
        button2: 'Generate API links',
        copy: 'copy',
        switch: 'Switch IP',
        agentPlaceholder:'Paste the generated proxy',
        button3:'Check Proxy'
    },

    trafficmanager: {
        title: 'Account amount',
        time_placeholder: 'Please select a date',
        placeholder1: 'Start date',
        placeholder2:'End date',
        day:'day',
        month:'month',
        year:'year',
        title2:'Account Management',
        add_account:'Add sub-account',
        name:'Account name',
        limit: 'Traffic Limit',
        flow: 'Traffic',
        date: 'Add time',
        status: 'State',
        mark:'Remark',
        action: 'Operate',
        edit:'Edit',
        disabled:'Disabled',
        enable:'Enable'
    },
    purchaseddetail: {
        title: 'Purchased IP',
        search1: 'Please enter the order name or number',
        search2:'Order Status',
        search3:'Region',
        search4: 'Expiration time',
        search5:'Automatic renewal',
        button1: 'Search',
        button2: 'Batch Renewal',
        button3:'Export',
        column1:'QR code',
        column2:'Expiration time',
        column3:'Region',
        column4:'Type',
        column5:'Proxy IP (IP: port: account: password)',
        column6:'Remark',
        column7:'Operate',
        action1:'Automatic renewal',
        action2:'Renewal',
        yes:'Yes',
        no:'No',
        tips:'Automatic renewal tips',
        message:'After opening, it will be automatically deducted from the account balance according to monthly renewal. If the balance is insufficient, the renewal will not be successful.',
        status1:'Paid',
        status2:'Not paid',
        status3:"All"
    },
    purchasedhistory: {
        title:'Purchase history',
        search1:'Please enter IP',
        search2:'Payment Status',
        search3:'Please select date',
        button1: 'Search',
        column1:'Order Number',
        column2:'Order Name',
        column3:'lump sum',
        column4:'Order Status',
        column5:'Payment Methods',
        column6:'Payment Time',
        total:'Total',
        item:'Ttems'
    },
    promotionrebate: {
        title: 'BitIP Promotion Rebate',
        subtitle:'Recommend BitIP to others. After successful registration, both parties will receive 200M dynamic traffic, and you can get 10% of the recharge income of the invitee permanently.',
        button1:'Invite Code',
        button2:'Invite Link',
        title2: 'Data Overview',
        title2_card1:'Number of Invitees',
        title2_card2:'Today Commission',
        title2_card3:'Total Commission',
        title2_card4:'Withdrawable amount',
        title2_card5:'Withdrawn amount',
        title2_button1:'Withdraw to account balance',
        title2_button2: 'Withdrawal',
        tab1:'My invitation history',
        tab2:'Withdrawal Record',
        tab1_column1:'Invitation time',
        tab1_column2:'Register Email',
        tab1_column3:'amount',
        tab1_column4:'Commission Rate',
        tab1_column5:'Subsequent commission rate',
        tab1_column6:'Commission Amount',
        tab1_column7:'State',
        tab2_column1:'Withdrawal Time',
        tab2_column2:'Withdrawable amount',
        tab2_column3:'Withdrawal amount',
        copy:'Copied',
        tip1:'Once the funds are withdrawn to the account balance, they cannot be withdrawn for cash but can be used to purchase packages.',
        tip2:'Contact customer service to withdraw cash after the balance reaches 100 yuan.',
        tip2_title:'Contact Customer Service',
        buttonName:'Confirm Withdrawal',
        buttonName1:'Confirm Withdrawal',
        status1:'No withdrawal',
        status2:'Withdrawn'
    },
    recharge: {
        title: 'Recharge Center',
        form1: 'Current available balance',
        form2:'Recharge order number',
        form3: 'Recharge amount',
        form4:'Payment Methods',
        button:'Confirm payment',
        pay1:'WeChat Pay',
        pay2:'Alipay',
        pay3:'Other Pay',
        confirmButton:'Confirm purchase'
    },
    userauth: {
        title: 'User Auth',
        form1:'Name',
        form2:'ID Num',
        form3:'Upload ID Num',
        button:'Confirm submission',
        tip_title:'Kind tips',
        tip1:'User authentication does not require waiting for review results',
        tip2:'Real-name information is user privacy information,',
        tip3:'No user information is published or disclosed.',
        title2:'After successfully completing the real-name authentication, you can get the BitIP real-name authentication reward',
        subtitle:'Flow',
        step1:'ID card authentication',
        step2:'Face Authentication',
        step2_title:'Please use Alipay to scan the QR code for face authentication',
        step2_button:'Return to previous page',
        step3:'Certification completed',
        step3_title:'Real-name authentication completed, 500M traffic obtained',
        form1_message:'Please enter a valid name',
        form2_message:'Please enter a valid ID card'
    },
    sub: {
        title: 'Add sub-account',
        form1: 'Enable',
        form2:'Account Name',
        form3:'Password',
        button:'Confirm',
        placeholder1:'Please select',
        placeholder2:'Please enter',
        form4:'remark',
        form5:'limit traffic',
        yes:'Yes',
        no:'No',
        form6:'Set traffic',
        edit:'Edit sub-account'
    },
    setting: {
        title:'Account Settings',
        form1: 'Real-name authentication',
        placeholder:'Unauthenticated',
        button1:'Go to Authentication',
        button_complated:'Certified',
        form2:'Email',
        form3:'Mobile phone number',
        form4:'Password',
        button2:'Modify',
        button3:'Confirm'
    },
    dyagent: {
        title1:'Dynamic Residential Agent',
        subtitle1:'100 million + high-purity family residential IP pool',
        subtitle2:'Unlimited concurrent requests',
        subtitle3:'1-120min variable IP aging',
        subButton1:'Free trial',
        subButton2:'Contact Us',
        title2:'Why choose BitIP Residential Agent',
        titl2_item1: 'Unlimited concurrent requests',
        title2_subtitle1:'Effective information capture solution based on AI and ML, performance proxy architecture. No bandwidth or browsing restrictions Compatible with a variety of browsers and tools.',
        titl2_item2: 'Formal source',
        title2_subtitle2:'We only offer and test the world is fastest real residential agents, 100% anonymity and 100% IP availability.',
        titl2_item3: 'Traffic never expires',
        title2_subtitle3:'Bitip provides cheap residential agency and high-quality services, and the traffic never expires.',
        titl2_item4: 'Easy to integrate',
        title2_subtitle4:'Through API interface, different systems can be integrated, development processes can be simplified, project cooperation can be promoted, and data exchange and expansion can be achieved.',
        title3:'Explore the best agency solution for you',
        title3_item1:'Germany',
        title3_item2:'USA',
        title3_item3:'UK',
        title3_item4:'Canada',
        title3_item5:'Mexico',
        title3_item6:'Brazil',
        title3_item7:'India',
        title3_item8:'Indonesia',
        title4: 'Buy a package',
        question1:'How are dynamic IP billed?',
        answer1_1:'Dynamic IP charges according to traffic, and the traffic calculation method is: uplink + downlink, and calculates the uploaded traffic plus the downloaded traffic sum.',
        question2:'How to test for free?',
        answer2_1:'After registering a new user, you can get 200M of traffic and test BitIP is dynamic proxy for free.',
        question3:'Why can not the proxy connect to the network?',
        answer3_1:'1. BitIP proxy IP can only be used on overseas networks. Please confirm whether it is in an overseas network environment.',
        answer3_2:'2. Confirm whether the traffic has been used up.',
        answer3_3:'If all of the above questions have been confirmed, you can try rebuilding the post-test, or contact the account manager for help.',
        question4:'I don’t know how to build an overseas network environment. Can I help me build an overseas environment?',
        answer4_1:`'BitIP does not assist any customer in building an overseas environment. And based on national laws and regulations, all domestic IP direct connections have been blocked.`,
        question5:'What is the case when my traffic is negative?',
        answer5_1:'Due to certain delays in data cache and traffic statistics, the balance may appear as negative after the system checks your traffic usage.',
        question6:'What are the supported proxy protocols?',
        answer6_1:'We support HTTP, HTTPS, and SOCKS5 proxy protocols to meet different application needs.'
    },
    staticagent: {
        title1:'Static residential agency',
        subtitle1:'Strong high IP purity and strong service adaptability',
        subtitle2:'100% exclusive',
        subtitle3:'Customized by enterprises',
        subButton1:'Free trial',
        subButton2:'Contact Us',
        title2:'Advantages of BitIP Static Residential Agent',
        titl2_item1: 'High IP purity, strong service adaptability',
        title2_subtitle1:'Strict resource screening logic, cleansing specific businesses, and ensuring that they meet business needs.',
        titl2_item2: '100% exclusive',
        title2_subtitle2:'Our agents are private or dedicated, which means that when you purchase a residential agent you will be the sole user of that IP.。',
        titl2_item3: 'Enterprise-level customization',
        title2_subtitle3:'Fully optimized for your goals to ensure the highest success rate at the fastest speed.',
        titl2_item4: 'Collect any data',
        title2_subtitle4:'Whether your use cases are SEO, social, advertising verification, price comparison or brand protection, BitIP is perfectly competent.',
        title3:'Fixed long-term native IP, suitable for business scenarios such as e-commerce account management, social media marketing, and enterprise acceleration that require a more stable and pure network environment.',
        tltle3_subtitle1:'Strictly choose real and pure native residential IP',
        tltle3_subtitle2:'Unlimited flow, unimpeded use',
        tltle3_subtitle3:'Support Http/Https/Socks5 protocol',
        tltle3_subtitle4:'Real-time delivery without waiting',
        title4:'Buy a package',

        question1:'How to bill static residential agents?',
        answer1_1:'Static residential agents are charged according to the number of IPs. You can choose to purchase a single IP. If you have a large demand, you can recharge your balance and purchase it more preferentially.',
        question2:'Do you support free static IP testing?',
        answer2_1:'To prevent IP abuse, static residential IP does not provide any free testing services. If you really need testing, you can contact us directly.',
        question3:'Are there any traffic restrictions for static residential IP?',
        answer3_1:'No. Static residential IP can be used without limiting the usage traffic during its useful life.',
        question4:'If the IP expires, can I continue to use the same IP after renewal?',
        answer4_1:'The IP can be renewed within 7 days after it expires. The renewal time is accumulated according to the first purchase time, and is not calculated from the renewal time.',
        question5:'Is the IP address inconsistent with the country selected at the time of purchase?',
        answer5_1:'Different browsers or websites use different IP identification databases. Some databases have update delays, and BitIP will be updated as soon as possible to ensure its accuracy.',
        question6:'Are static residential agents shared or exclusive?',
        answer6_1:'Static proxy is exclusive to you, and you don’t need to worry about the IP being shared or abused by other users, ensuring the purity of the proxy.'
    },
    buying: {
        title1: 'Package purchase',
        title2:'Balance recharge',
        form1:'Product Name',
        form2:'Order number',
        form3:'Recharge amount',
        form4:'Payment method',
        form5:'Current available balance',
        subtitle:'Payment consent',
        content:'Refund Agreement',
        tips:'Pay fees',
        content2:'Other Payment please contact customer service'
    },
    plan: {
        title: 'BitIP promotion rebate plan, one-time promotion, permanent benefits. Invite users, 10% commission rebate with no upper limit',
        button:'Join Now',
        item1_content1:'Commission rebates and permanent income',
        item1_content2:'¥No limit',
        item1_content3:'One-time cash rebate',
        item1_content4:'Register now to get 200M dynamic traffic',
        item1_content5:'Real-name authentication gives 500M dynamic traffic',
        item2_content1:'Send 200M',
        item2_content2:'Dynamic flow',
        item2_content3:'Register successfully and get free',
        item3_content:'Commission withdrawal',
        item4_content:'Permanent income',
        item5_content1:'High commissions',
        item5_content2:'Permanently receive a commission proportional to the amount of all packages purchased by invited customers',

        title2:'How to join the BitIP promotion rebate program',
        title2_subtitle:'* The promotion plan is only applicable to how to join the BitIP promotion rebate plan. More package promotions will be launched soon, so stay tuned!',
        step:'step',
        step1:'Register Create your BitIP account',
        step2:'Check your exclusive invitation link in the account background',
        step3:'Share Link - Start Earning Money',
        step4:'Contact customer service to withdraw commission'
    }
}

export const zh = {
    login: {
        passwordLogin: '密码登录',
        smsLogin: '短信登录',
        loginTitle: '全球住宅代理IP企业级大数据采集解决方案',
        phonePlaceholder: '请输入手机号/账号',
        passwordPlaceholder: '请输入密码',
        agree: '我已阅读并同意',
        userServiceAgreement: 'BITIP用户服务协议',
        privacyPolicy: 'BITIP隐私协议',
        login: '登录',
        forgetPassword: '忘记密码',
        notAccount:'暂无账号?',
        registerNow: '立即注册',
        phoneValidate: '请输入手机或者账号',
        passwordValidate: '请输入密码',
        phoneTips: '手机 / 账号',
        passwordTips: '密码',
        modalPolicy: '服务协议及隐私保护',
        modalTips: '为了更好地为您提供服务，保障用户合法权益，帮请您阅读并同意以下协议',
        agreeLogin: '同意并登录',
        disagree: '不同意',
        textLogin: '请输入手机号',
        textTips: '手机',
        textValidate: '请输入正确的手机号',
        verifyCode: '请输入验证码',
        sendCode: '发送验证码',
        verifyTips: '验证码',
        register:'注册',
        haveAccount:'已有账号?',
        passwordValidateNew: '请输入6-12位的密码',
        confirmMessage: '确认',
        email:'邮箱',
        emailValidate:'请输入合法的邮箱',
        emailPlaceholder: '请输入邮箱',
        finshSetting: '已完成设置?',
        newPassword: '请输入新密码',
        confirmPassword: '两次密码不一致',
        confirmPassTips: '确认密码',
        captchaVerifyTitps: '请滑动验证码',
        sendSms:'已发送,请查收',
        exit:'退出登录',
        Backstage:'仪表盘',
        registerTip:'送200M',
        modityTips:'修改成功',
        registerSuccess:'注册成功',
        newPassTip:'新密码',
        modifyMessage:'修改成功'
    },
    first: {
        title:'全球住宅代理',
        title1:'比特',
        content:'真实住宅网络覆盖',
        content2:'国家，高速稳定支持多场景数据采集，智能路由保障隐私安全，助力企业高效拓展全球市场！',
        subtitle:'企业级大数据采集解决方案',
        item1:'亿+真实住宅网络',
        item2:'IP纯净来源合规',
        item3:'99.9%连通率',
        item4:'7X24 AI筛选',
        freeUse:'免费试用',
        contact:'联系我们',
        cardTitle1:'城市级定位',
        cardContent1:'动态全球覆盖和精准的地理定位，支持IP轮换',
        cardTitle2:'SOCKS5/HTTP/HTTPS协议',
        cardContent2: '使用专有算法对通信协议进行加密',
        cardTitle3: '住宅ISP',
        cardContent3: '精选高纯净度原生静态IP，安全管理各类电商账号。',
        cardTitle4: '子账号管理',
        cardContent4: '子账号管理 企业级账号管理，实时监控流量',
        cardTitle5: '技术支持',
        cardContent5: '技术支持 专业团队1V1全程支持，提供定制化解决方案',
        tips: '（所有产品仅支持大陆以外网络环境使用）'
    },
    second: {
        title: '高纯净、高稳定性代理IP',
        select1:'动态住宅代理',
        select2: '静态住宅代理',
        dynamicContent: '来自全球真实家庭住宅设备，适用于IP数量需求 大且短时使用的业务场景',
        dynamicItem1: '亿+高纯净家庭住宅IP池',
        dynamicItem2: '无限并发请求',
        dynamicItem3: '1-120min 可变IP时效',
        dynamicItem4: '支持Http/Https/Socks5协议',
        dynamicItem5: '支持API接入，网络更稳定',
        dynamicButton:'免费试用',
        dynamicContent1:'固定长时效原生IP，适用于电商账号管理、社媒营销、企业加速等需要更稳定纯净网络环境的业务场景',
        dynamicItem6:'严选真实纯净原生住宅IP',
        dynamicItem7:'不限流量，畅用无阻',
        dynamicItem8:'支持Http/Https/Socks5协议',
        dynamicItem9:'实时交付，无需等待',
        dynamicButton1:'了解更多'
    },
    third: {
        title: '服务与规模',
        item1title: '全球资源',
        item1Subtitle:'全球资源',
        item1Content:'与全球多家ISP合作，确保IP资源的丰富性和稳定性。',
        item2title: '专业团队',
        item2Subtitle:'亿级代理资源池',
        item2Content:'IPIDEA自建企业级纯净IP池，严格筛选1亿多个优质IP资源，满足企业 大规模数据采集业务，有效降低企业成本',
        item3title: '高性价比',
        item3Subtitle:'高性价比',
        item3Content:'提供灵活的价格方案，满足不同规模企业的需求。',
        item4title: '安全可靠',
        item4Subtitle:'安全可靠',
        item4Content:'严格的数据保护措施，确保您的数据安全。',
        item5title: '高匿名性',
        item5Subtitle:'高匿名性',
        item5Content:'所有IP均来自真实的家庭宽带用户，确保高匿名性和低封禁率。'
    },
    fourth: {
        title: '解锁全球网络资源，赋能您的数字业务',
        subtitle1: '220+',
        content1: '全球可选地区',
        subtitle2: '亿级',
        content2: '承载并发',
        subtitle3: '99.9%',
        content3: '高IP可用率',
        ger:'德国',
        us: '美国',
        uk:'英国',
        can:'加拿大',
        ind:'印度'
    },
    fifth: {
        title: '应用场景',
        subtitle1: '数据抓取与爬虫',
        content1: '抓取电商、社交媒体、搜索引擎等数据，避免IP被封禁。支持高频率请求和大规模数据采集。',
        subtitle2: '广告验证',
        content2: '验证广告在不同地区的展示效果，确保广告投放的准确性。模拟真实用户行为，获取真实的广告数据。',
        subtitle3: '价格监控',
        content3: '监控竞争对手的价格变化，获取市场动态。支持多地区、多平台的价格监控。',
        subtitle4: 'SEO监控',
        content4: '检查网站在不同地区的搜索排名，优化SEO策略。支持多搜索引擎和多关键词监控。',
        subtitle5: '社交媒体管理',
        content5: '管理多个社交媒体账号，避免账号关联。支持多平台、多账号的自动化操作。',
        subtitle6: '市场调研',
        content6: '获取不同地区的市场数据，支持商业决策。支持多语言、多地区的调研需求。',
        more: '了解更多'
    },
    sixth: {
        title: '开启全球网络的无界之门',
        content: '免费体验5个浏览器环境',
        button1: '免费试用',
        button2: '联系我们'
    },
    seventh: {
        title: '集成至您的工具'
    },
    acvitity: {
        title: '注册就送200M动态流量',
        subtitle: '立减¥100'
    },
    contact: {
        title1: 'QQ客服',
        title2: '微信客服',
        title3: '微信公众号',
        title4: 'Telegram'
    },
    navMenu: {
        title1: '套餐购买',
        package_title1:'套餐购买',
        package_title2:'余额充值',
        package_subtitle1: '动态住宅IP',
        package_subtitle1_tips:'低至¥4.5/GB',
        package_subtitle2:'静态住宅IP',
        package_subtitle2_tips:'独享原生超纯净',
        package_subtitle3: '充值就送',
        package_subtitle3_tips:'动态住宅套餐',
        package_subtitle4: '静态住宅套餐',
        package_title3: '最新活动',
        title2: '动态住宅代理',
        title3:'代理产品',
        title4: '帮助中心',
        title5: '安全合规',
        title6: '企业定制',
        title7: '推广计划',
        title8: '静态住宅代理'
    },
    footer: {
        describe: '电话/微信',
        title1: 'BitIP',
        title1_subtitle1: '动态住宅代理',
        title1_subtitle2: '静态住宅代理',

        title2: '教程中心',
        title2_subtitle1: 'API文档',
        title2_subtitle2: '产品使用教程',
        title3: '关于我们',
        title3_subtitle1: '隐私协议',
        title3_subtitle2: '服务协议',
        title3_subtitle3:'安全合规',
        title3_subtitle4:'企业定制',
        title3_subtitle5: '推广计划',
        title3_subtitle6: '合作伙伴',
        title4_subtitle7:'退款协议',
        title4: '全球代理',
        title4_subtitle1: '美国原生家庭带宽',
        title4_subtitle2: '英国原生家庭带宽',
        title4_subtitle3:'德国原生家庭带宽',
        title4_subtitle4:'新加坡原生家庭带宽',
        title4_subtitle5: '泰国原生家庭带宽',
    },
    safety: {
        title: '为您的业务提供安全可靠的网络环境',
        subtitle: '在数字化时代，数据安全与合规性是企业成功的关键。BITIP 始终将安全放在首位，致力于为用户提供安全、合规、可靠的代理服务，确保您的业务在全球范围内无后顾之忧。',
        title2: 'BITIP 的安全承诺',
        subtitle2: 'BITIP 采用先进的加密技术（如 SSL/TLS），确保您的数据在传输过程中始终处于加密状态，防止被窃取或篡改。我们严格遵守隐私保护政策，绝不泄露用户数据。',
        title2_item1_title: '实时监控与威胁防御',
        title2_item1_content: 'BITIP 的安全团队 24/7 实时监控网络流量，快速识别并防御潜在的网络攻击（如 DDoS、恶意爬虫等），确保您的业务始终稳定运行。',
        title2_item2_title: '合规性与透明度',
        title2_item2_content: '我们严格遵守全球主要国家和地区的法律法规，确保您的业务在全球范围内合规运营。同时，我们提供透明的服务协议和使用政策，让您清晰了解数据的使用方式。',
        title2_item3_title: '零日志政策',
        title2_item3_content: 'BITIP 采用严格的零日志政策，不记录用户的浏览历史、访问数据或任何敏 感信息，确保您的隐私得到最大程度的保护。',
        title3: '安全标准',
        subtitle3: '符合ISO27001信息安全管理体系，SOC 2合规标准等行业高标准',
        title3_item1_title1: 'ISO 27001',
        title3_item1_content: '信息安全管理体系',
        title3_item2_title2:'SOC 2',
        title3_item2_content: '合规标准'
    },
    extra: {
        title: '最适合您的代理方案'
    },
    service: {
        title1: '企业定制服务',
        content1: '在当今数字化时代，企业需要高效、可靠的网络工具来应对复杂的业务需求。BITIP 深知每个企业的独特性，因此我们提供企业定制服务，为您量身打造专属的代理解决方案，助力您的业务在全球范围内无界拓展。',
        title2: '定制服务',
        title2_subtitle1: '高度定制化',
        title2_content1: '我们根据您的业务需求，提供从IP类型、地理位置到并发连接数等全方位的定制服务，确保您的网络工具完全匹配业务场景。',
        title2_subtitle2: '专业团队支持',
        title2_content2: 'BITIP 拥有经验丰富的技术团队，为您提供7x24小时的专业支持，确保您的业务始终顺畅运行。',
        title2_subtitle3: '安全与隐私保障',
        title2_content3: '我们采用先进的加密技术和严格的数据保护措施，确保您的业务数据安全无虞。',
        title3:'定制流程',
        title3_title1:'需求沟通',
        title3_title1_content:'与我们的专家团队沟通,明确您的业务需求和目标。',
        title3_title2:'方案设计',
        title3_title2_content:'根据您的需求，量身定制代理方案，包括IP类型、地理位置、并发数等。',
        title3_title3:'部署与测试',
        title3_title3_content:'快速部署定制方案，并进行全面测试，确保性能能达到预期。',
        title3_title4:'持续优化',
        title3_title4_content:'根据业务发展，持续优化代理服务，确保始终满足您的需求',
        title4:'众多企业的共同选择'
        // subtitle3: '为全球30000+企业提供资源、技术、服务等多维度支持，并开放IPIDEA全球生态资源，合作共赢',
        // title3_card1_title: '商业道德',
        // title3_card1_subtitle:'为全球30000+企业提供资源、技术、服务等多维度 支持，并开放IPIDEA全球生态资源，合作共赢',
        // title3_card1_content:'为全球30000+企业提供资源、技术。',
        // title3_card1_content1:'为全球30000+企业提供资源、技术。',
        // title3_card1_content2:'为全球30000+企业提供资源、技术。',
        // title3_card2_title: '合法代理池',
        // title3_card2_subtitle:'住宅代理池来自精心挑选且合乎道德的合作伙伴。',
        // title3_card3_title: '供应商审核流程',
        // title3_card3_subtitle:'整个供应连实时了严格、全面的审核流程，避免任何潜在的供应商故障。',

        // title4: '企业基本信息',
        // form1_label:'您的使用范围',
        // form1_placeholder1:'包月套餐',
        // form1_placeholder2: '包月套餐',
        // form2_label:'代理类型',
        // form2_placeholder: '包月套餐',

        // form3_label: '企业基本信息',
        // form3_placeholder1: '公司名称',
        // form3_placeholder2: '手机号',
        // form3_placeholder3: '邮箱（选填）',

        // form4_label: '代理类型',
        // form4_placeholder: '其他说明',
        // button:'提交'
    },
    setmenu: {
        title: 'BitIP代理优惠套餐类型',
        subtitle1: '动态套餐',
        subtitle2: '静态套餐',
        subtitle3: '余额充值',
        discount:'优惠购买',
        menu1: '入门',
        price:'单价',
        originPrice:'原价',
        menu2: '基础',

        menu3: '常规',

        menu4: '专业',

        menu5: '企业',

        menu6: '无限',
        menu6_title:'定制',
        menu6_button:'联系客服',
        title2:'套餐包括什么？',
        content1: '流量用不过期',
        content2: '亿级超大 IP池',
        content3: '无限并发',
        content4: '可变时效',
        content5: '精准城市定位',
        content6:'子账号流量分配',
        bottom_title: '常见问题',
        question1:'产品套餐和额度充值使用代理有什么区别？',
        answer1: '',
        question2:'产品套餐和额度充值使用代理有什么区别？',
        answer2: '',
        question3:'产品套餐和额度充值使用代理有什么区别？',
        answer3: '',
        question4:'产品套餐和额度充值使用代理有什么区别？',
        answer4: '',
        question5:'产品套餐和额度充值使用代理有什么区别？',
        answer5: '',
        question6:'产品套餐和额度充值使用代理有什么区别？',
        answer6: '',

        location:'原生住宅双ISP',
        location2:'住宅单ISP',
        type1:'单ISP',
        type2:'双ISP',
        timeSelect:'时间选择',
        time1:'1个月',
        time2:'2个月',
        time3: '一季度',
        time4:'半年',
        time5: '一年',
        off: '折',
        clear:'清空',
        areas:'总地区',
        ips: '总IP数',
        allPrice: '总价',
        buyButton: '立即购买',
        number: '个',
        arrival: '到账',
        recharge: '充值',
        deliver: '送',

        recharge_title: '充值余额就送,享受更多优惠',
        recharge_subtitle: '余额可用于购买动、静态套餐及续费',
        illustrate: '优化价格说明'
    },
    backend_menu: {
        menu1:'动态住宅',
        menu1_sub1:'代理生成',
        menu1_sub2:'购买流量',
        menu1_sub3: '流量管理',
        menu2: '静态住宅',
        menu2_sub1: '购买代理',
        menu2_sub2:'已购代理',
        menu3: '购买记录',
        menu4: '推广返利',
        menu5:'实名认证',
        local:'当前IP',
        Balance:'账户余额',
        recharge:'充值',
        welcome:'欢迎你',
        account:'账户总览',
        authentication:'实名认证',
        setting:'账户设置',
        tip:'（所有产品仅支持大陆以外网络环境使用）'
    },
    proxycity: {
        card_title1: '剩余流量',
        card_title2:'总流量',
        card_title3: '已使用流量',
        card_button:'购买流量',
        card_button1:'流量管理',
        card_button_title:'添加子账号',
        describe1: '描述',
        describe2: '描述',
        describe3: '描述',
        card1: '动态住宅代理生成',
        card2:'卡片2',
        form1:'选择认证账户',
        form1_placeholder: '请选择',
        form2:'选择国家',
        form2_placeholder: '请选择',
        form3: '选择地区',
        form3_placeholder:'请选择',
        form4: '选择城市',
        form4_placeholder:'请选择',
        form5: 'IP时效',
        form5_placeholder: '请选择',
        form6: '切换IP',
        form6_placeholder:'自动切换IP',
        form7_placeholder: '请选择',
        form7: '选择数量',
        button1: '生成代理IP',
        button2: '生成API链接',
        copy: '复制',
        switch: '切换IP',
        agentPlaceholder:'粘贴生成的代理',
        button3:'检查代理'
    },
    trafficmanager: {
        title: '账户额度',
        time_placeholder: '请选择日期',
        placeholder1: '开始日期',
        placeholder2:'结束日期',
        day:'日',
        month:'月',
        year:'年',
        title2:'账户管理',
        add_account:'新增子账号',
        name:'账号名称',
        limit: '流量使用限制',
        flow: '流量消耗',
        date: '添加时间',
        status: '状态',
        mark:'备注',
        action: '操作',
        edit:'编辑',
        disabled:'禁用',
        enable:'启用'
    },
    purchaseddetail: {
        title: '已购IP',
        search1: '请输入订单名称或者编号',
        search2:'订单状态',
        search3:'地区',
        search4: '过期时间',
        search5:'是否自动续费',
        button1: '搜索',
        button2: '批量续费',
        button3:'导出',
        column1:'二维码',
        column2:'过期时间',
        column3:'地区',
        column4:'类型',
        column5:'代理IP(IP:端口:账号:密码)',
        column6:'备注',
        column7:'操作',
        action1:'自动续费',
        action2:'续费',
        yes:'是',
        no:'否',
        tips:'自动续费提示',
        message:'开启后从账户余额内按每月续费自动扣除，余额不足则续费不成功',
        status1:'已支付',
        status2:'未支付',
        status3:'全部'
    },
    purchasedhistory: {
        title:'购买记录',
        search1:'请输入IP',
        search2:'支付状态',
        search3:'请选择日期',
        button1: '搜索',
        column1:'订单号',
        column2:'订单名称',
        column3:'总金额',
        column4:'订单状态',
        column5:'支付方式',
        column6:'支付时间',
        total:'共',
        item:'条'
    },
    promotionrebate: {
        title: 'BitIP推广返利',
        subtitle:'向他人推荐BitIP,注册成功后双方各送200M动态流量，可获得被邀请者永久10%的充值收益',
        button1:'邀请码',
        button2:'邀请链接',
        title2: '数据概述',
        title2_card1:'邀请人数',
        title2_card2:'今日佣金',
        title2_card3:'佣金总额',
        title2_card4:'可提取金额',
        title2_card5:'已提取金额',
        title2_button1:'提取至账户余额',
        title2_button2: '提取',
        tab1:'我的邀请历史',
        tab2:'提款记录',
        tab1_column1:'邀请时间',
        tab1_column2:'注册电子邮件',
        tab1_column3:'数量',
        tab1_column4:'佣金比率',
        tab1_column5:'后续佣金比率',
        tab1_column6:'佣金金额',
        tab1_column7:'状态',
        tab2_column1:'提款时间',
        tab2_column2:'可提取金额',
        tab2_column3:'提款金额',
        copy:'已复制',
        tip1:'提取至账户余额后不可提现，可用于购买套餐使用。',
        tip2:'满100元后联系客服提现。',
        tip2_title:'联系客服',
        buttonName:'确认提取',
        buttonName1:'确认提现',
        status1:'未提现',
        status2:'已提现'

    },
    recharge: {
        title: '充值中心',
        form1: '当前可用余额',
        form2:'充值订单号',
        form3: '充值金额',
        form4:'支付方式',
        button:'确认支付',
        pay1:'微信支付',
        pay2:'支付宝支付',
        pay3:'余额支付',
        confirmButton:'确认购买'
    },
    userauth: {
        title: '实名认证',
        form1:'姓名',
        form2:'身份证证件号',
        form3:'上传证明身份证号',
        button:'确认提交',
        tip_title:'温馨提示',
        tip1:'1、实名认证无需等待审核结果',
        tip2:'2、实名信息属用户隐私信息, ',
        tip3:'不公开或透露用户信息。',
        title2:'成功完成实名认证后,可获得BitIP实名认证奖励',
        subtitle:'流量',
        step1:'身份证认证',
        step2:'人脸认证',
        step2_title:'请用支付宝扫码采集人脸认证',
        step2_button:'返回上一页',
        step3:'认证完成',
        step3_title: '实名认证完成,已获得500M流量',
        form1_message:'请输入合法的姓名',
        form2_message:'请输入合法的身份证'

    },
    sub: {
        title: '添加子账号',
        form1: '启用',
        form2:'账户名',
        form3:'密码',
        form4:'备注',
        form5:'是否限制流量',
        form6:'设置流量',
        yes:'是',
        no:'否',
        button:'确认',
        placeholder1:'请选择',
        placeholder2:'请输入',
        edit:'编辑子账号'
    },
    setting: {
        title:'账户设置',
        form1: '实名认证',
        placeholder:'未认证',
        button1:'去认证',
        button_complated:'已认证',
        form2:'邮箱',
        form3:'绑定手机号',
        form4:'密码',
        button2:'修改',
        button3:'确认',
        title_modal1:'修改邮箱',
        title_modal2:'修改密码',
    },
    dyagent: {
        title1:'动态住宅代理',
        subtitle1:'亿+高纯净家庭住宅IP池',
        subtitle2:'无限并发请求',
        subtitle3:'1-120min 可变IP时效',
        subButton1:'免费试用',
        subButton2:'联系我们',
        title2:'为什么选择BitIP住宅代理',
        titl2_item1: '无限并发请求',
        title2_subtitle1:'基于AI和ML的有效信息捕获解决方案，性能代理架构。无带宽或浏览限制 与各种浏览器和工具兼容。',
        titl2_item2: '正规来源',
        title2_subtitle2:'我们只提供和测试世界上最快的真实住宅代理，100%匿名性和100%IP可用性。',
        titl2_item3: '流量永不过期',
        title2_subtitle3:'Bitip提供便宜的住宅代理和优质的服务，流量永不过期。',
        titl2_item4: '易于集成',
        title2_subtitle4:'通过API接口可集成不同系统、简化开发流程、促进项目合作,实现数据交换与扩展',
        title3:'探索最适合你的代理方案',
        title3_item1:'德国',
        title3_item2:'美国',
        title3_item3:'英国',
        title3_item4:'加拿大',
        title3_item5:'墨西哥',
        title3_item6:'巴西',
        title3_item7:'印度',
        title3_item8:'印度尼西亚',
        title4: '购买套餐',
        question1:'动态IP是怎么计费的？',
        answer1_1:'动态IP按照流量进行收费，流量计算方式为：上行+下行，计算上传的流量加下载的流量总和。',
        question2:'如何免费测试？',
        answer2_1:'新用户注册后，即可获取200M的流量，免费测试BitIP的动态代理。',
        question3:'为什么代理无法连接到网络？',
        answer3_1:'1. BitIP代理IP仅能在境外网络下使用，请确认是否处于境外网络环境。',
        answer3_2:'2. 确认流量是否已用完。',
        answer3_3:'如果以上问题都已经确认无误，您可以尝试重新生成后测试，或者联系客户经理获取帮助。',
        question4:'我不会搭建境外网络环境，能不能帮我搭建境外环境？',
        answer4_1:'BitIP不协助任何客户进行境外环境的搭建。 并且已基于国家法律法规，屏蔽了所有国内IP直连。',
        question5:'我的流量出现了负数是什么情况？',
        answer5_1:'由于数据缓存和流量统计存在一定延迟，系统在校验您的流量使用情况后，可能导致余额显示为负数。',
        question6:'支持的代理协议有哪些？',
        answer6_1:'我们支持HTTP、HTTPS、SOCKS5代理协议，以满足不同的应用需求。'
    },
    staticagent: {
        title1:'静态住宅代理',
        subtitle1:'高IP纯度强，业务适配能力强',
        subtitle2:'100%独享',
        subtitle3:'企业定制',
        subButton1:'免费试用',
        subButton2:'联系我们',
        title2:'BitIP静态住宅代理的优势',
        titl2_item1: '高IP纯净度，业务适配能力强',
        title2_subtitle1:'严格的资源筛选逻辑，针对特定业务进行清洗，确保贴合业务需要。',
        titl2_item2: '100%独享',
        title2_subtitle2:'我们的代理是私人的或专用的，这意味着当您购买住宅代理时使用静态IP 地址，您将是该IP 的唯一使用者。',
        titl2_item3: '企业级定制',
        title2_subtitle3:'根据您的目标完全优化的私人定制代理，以确保以最快的速度获得最高的成功率。',
        titl2_item4: '收集任何数据',
        title2_subtitle4:'无论您的用例是SEO、社交、广告验证、价格比较还是品牌保护，BitIP都可以完美胜任。',
        title3:'固定长时效原生IP，适用于电商账号管理、社 媒营销、企业加速等需要更稳定纯净网络环境 的业务场景',
        tltle3_subtitle1:'严选真实纯净原生住宅IP',
        tltle3_subtitle2:'不限流量，畅用无阻',
        tltle3_subtitle3:'支持Http/Https/Socks5协议',
        tltle3_subtitle4:'实时交付，无需等待',
        title4:'购买套餐',
        question1:'静态住宅代理如何计费？',
        answer1_1:'静态住宅代理按照IP个数计费，您可选择单条IP购买，需求量大可以充值余额后购买更优惠。',
        question2:'你们支持静态IP免费测试吗?',
        answer2_1:'为防止IP滥用，静态住宅IP暂不提供任何免费测试服务，如确有测试需要，可直接联系我们。',
        question3:'静态住宅IP有流量限制吗？',
        answer3_1:'没有。静态住宅IP在使用期内可以不限使用流量。',
        question4:'如果IP过期了，续费后可以继续使用同一个IP吗？',
        answer4_1:'IP过期后7天内可以续费，续费时长根据首次购买时间相应累加，并非是从续费时刻开始计算。',
        question5:'IP地址与购买时选择的国家不一致?',
        answer5_1:'不同的浏览器或网站使用的IP识别数据库不尽相同，某些数据库存在更新延迟，BitIP会尽快更新以保证其准确性。',
        question6:'静态住宅代理是共享的还是独享的？',
        answer6_1:'静态代理是个人独享的，您无需担心IP被其他用户共享或滥用，确保代理的纯净度。'

    },
    buying: {
        title1: '套餐购买',
        title2:'余额充值',
        form1:'产品名称',
        form2:'订单号',
        form3:'充值金额',
        form4:'支付方式',
        form5:'当前可用余额',
        subtitle:'支付即表示同意',
        content:'退款协议',
        tips:'支付费用',
        content2:'其他支付方式联系客服'
    },
    plan: {
        title: 'BitIP推广返佣计划，一次推广，永久收益 邀请用户，10%佣金返现无上限',
        button:'马上加入',
        item1_content1:'佣金返现和永久收益',
        item1_content2:'¥无上限',
        item1_content3:'一次性现金返佣',
        item1_content4:'注册者送200M动态流量',
        item1_content5:'实名认证送500M动态流量',
        item2_content1:'送200M',
        item2_content2:'动态流量',
        item2_content3:'注册成功就送',
        item3_content:'佣金提现',
        item4_content:'永久收益',
        item5_content1:'高额佣金',
        item5_content2:'永久获得被邀客户购买所有 套餐金额的比例佣金',

        title2:'如何加入BitIP推广返佣计划',
        title2_subtitle:'* 推广计划仅适用于如何加入BitIP推广返佣计划，更多套餐推广即将上线，敬请期待！',
        step:'步骤',
        step1:'注册创建您的BitIP账户',
        step2:'账户后台查看您的专属邀请链接',
        step3:'分享链接-开始赚钱',
        step4:'联系客服提取佣金'
    }
}